version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.10.0-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      # Only connections from localhost are allowed without credentials.
      # Kind deployment is using this service as external broker which is not a local connection.
      RABBITMQ_DEFAULT_USER: developer
      RABBITMQ_DEFAULT_PASS: secret
  mongodb:
    image: mongo:5.0.8
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: secret
  verdaccio:
    image: verdaccio/verdaccio:5.10.2
    ports:
      - '4873:4873'
