$schema: https://json-schema.org/draft/2019-09/schema
$id: https://schemas.kookaburra.dev/0.0.0/manifest

type: object
properties:
  prototype:
    properties:
      prototype:
        $ref: '#/properties/prototype'
      path:
        type: string
      operations:
        type: array
        items:
          properties:
            name:
              $ref: '#/properties/operations/items/properties/name'
            bridge:
              $ref: '#/properties/bridge'

  domain:
    $ref: 'definitions#/definitions/token'
  name:
    $ref: 'definitions#/definitions/token'

  entity:
    type: object
    properties:
      storage:
        type: string
        default: '@kookaburra/storages.mongodb'
      schema:
        $ref: 'definitions#/definitions/schema'
        type: object
        properties:
          type:
            default: object
            const: object
          additionalProperties:
            default: false
            const: false
          properties:
            type: object
            propertyNames:
              $ref: 'definitions#/definitions/token'
    required: [schema]
    additionalProperties: false

  bindings:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      type: string
      not:
        const: '@kookaburra/bindings.loop' #loop is for system use only
    default: ['@kookaburra/bindings.http', '@kookaburra/bindings.amqp']

  bridge:
    type: string

  remotes:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      type: string

  operations:
    type: array
    minItems: 1
    items:
      type: object
      properties:
        name:
          $ref: 'definitions#/definitions/token'
        type:
          enum: [transition, observation]
        target:
          enum: [entry, entries]
        bridge:
          type: string
        bindings:
          $ref: '#/properties/bindings'
        input:
          $ref: 'definitions#/definitions/schema'
        output:
          $ref: 'definitions#/definitions/schema'
        query:
          type: boolean
      required: [name, type, target]
      additionalProperties: false

  events:
    type: array
    minItems: 1
    items:
      type: object
      properties:
        label:
          $ref: 'definitions#/definitions/token'
        bridge:
          type: string
        path:
          type: string
        conditional:
          type: boolean
          default: false
        subjective:
          type: boolean
          default: false
      required: [label, bridge, path]
      additionalProperties: false

additionalProperties: false
