$schema: https://json-schema.org/draft/2019-09/schema
$id: https://schemas.kookaburra.dev/0.0.0/manifest

definitions:
  binding:
    type: string
    not:
      const: '@kookaburra/bindings.loop' #loop is for system use only

type: object
properties:
  prototype:
    type: object
    nullable: true
    properties:
      prototype:
        $ref: '#/properties/prototype'
      path:
        type: string
      operations:
        type: object
        propertyNames:
          $ref: 'definitions#/definitions/token'
        patternProperties:
          '.*':
            type: object
            properties:
              bridge:
                $ref: '#/properties/bridge'

  domain:
    $ref: 'definitions#/definitions/token'
  name:
    $ref: 'definitions#/definitions/token'

  entity:
    type: object
    properties:
      storage:
        type: string
        default: '@kookaburra/storages.mongodb'
      schema:
        $ref: 'definitions#/definitions/schema'
        type: object
        properties:
          type:
            default: object
            const: object
          additionalProperties:
            default: false
            const: false
          properties:
            type: object
            propertyNames:
              $ref: 'definitions#/definitions/token'
    required: [ schema ]
    additionalProperties: false

  bindings:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      $ref: '#/definitions/binding'

  bridge:
    type: string

  remotes:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      $ref: 'definitions#/definitions/fqn'

  operations:
    type: object
    propertyNames:
      $ref: 'definitions#/definitions/token'
    patternProperties:
      '.*':
        type: object
        properties:
          type:
            enum: [ transition, observation ]
          target:
            enum: [ entry, entries ]
          bridge:
            type: string
          bindings:
            $ref: '#/properties/bindings'
          input:
            $ref: 'definitions#/definitions/schema'
          output:
            $ref: 'definitions#/definitions/schema'
          query:
            type: boolean
        required: [ type, target ]
        additionalProperties: false
    additionalProperties: false

  events:
    type: object
    propertyNames:
      $ref: 'definitions#/definitions/token'
    patternProperties:
      '.*':
        type: object
        properties:
          bridge:
            type: string
          path:
            type: string
          binding:
            $ref: '#/definitions/binding'
          conditioned:
            type: boolean
            default: false
          subjective:
            type: boolean
            default: false
        required: [ bridge, path ]
        additionalProperties: false

  receivers:
    type: object
    propertyNames:
      $ref: 'definitions#/definitions/locator'
    patternProperties:
      '.*':
        type: object
        properties:
          transition:
            $ref: 'definitions#/definitions/token'
          bridge:
            type: string
          path:
            type: string
        required: [ transition, bridge, path ]
        additionalProperties: false

additionalProperties: false
