# This file just helps with IDE autocompletion and helm debugging. Actually dynamically replaced by ../values.js.
compositions:
  - name: todos
    image: localhost:5000/todos:0.0.0
    replicas: 2
    components:
      - todos-tasks
      - todos-stats
  - name: messages
    image: localhost:5000/messages:0.0.0
    replicas: 2
    components:
      - users-users
# TODO: create services only if sync binding is being used by a component
components:
  - todos-tasks
  - todos-stats
  - users-users
