$schema: https://json-schema.org/draft/2019-09/schema
$id: https://schemas.toa.io/0.0.0/bindings/amqp/annotations

type: string
pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'
