$schema: http://json-schema.org/draft-07/schema
$id: https://schemas.kookaburra.dev/0.0.0/manifest

definitions:
  token:
    type: string
    pattern: ^[a-zA-Z]+([_-a-zA-Z0-9]*[a-zA-Z0-9]+)?$

type: object
properties:
  domain:
    $ref: '#/definitions/token'
  name:
    $ref: '#/definitions/token'

  entity:
    type: object
    properties:
      schema:
        $ref: http://json-schema.org/draft-07/schema
        type: object
        properties:
          type:
            default: object
            const: object
          additionalProperties:
            default: false
            const: false
          properties:
            type: object
            propertyNames:
              $ref: '#/definitions/token'
            properties:
              id:
                default:
                  type: string
                const:
                  type: string
      storage:
        type: object
        default:
          connector: '@kookaburra/storages.mongodb'
        properties:
          connector:
            default: '@kookaburra/storages.mongodb'
            type: string
    required: [schema]
    additionalProperties: false

  bindings:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      type: string
      not:
        const: '@kookaburra/bindings.loop' #loop is for system use only
    default: ['@kookaburra/bindings.http', '@kookaburra/bindings.amqp']

  remotes:
    type: array
    uniqueItems: true
    minItems: 1
    items:
      type: string

  operations:
    type: array
    minItems: 1
    items:
      type: object
      properties:
        name:
          $ref: '#/definitions/token'
        type:
          enum: [transition, observation]
        target:
          enum: [entry, set]
        bridge:
          type: string
          default: '@kookaburra/bridges.javascript.native'
        bindings:
          $ref: '#/properties/bindings'
        input:
          $ref: http://json-schema.org/draft-07/schema
          default:
            type: 'null'
        output:
          $ref: http://json-schema.org/draft-07/schema
          default:
            type: 'null'
        .bridge:
          type: object
      required: [name, type, target, bridge]
      additionalProperties: false

required: [domain, operations]
additionalProperties: false
