{{- range .Values.compositions }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: composition-{{ required "deployment name is required" .name }}
spec:
  replicas: {{ .replicas | default 2 }}
  selector:
    matchLabels:
      toa.io/composition: {{ .name }}
  template:
    metadata:
      labels:
        toa.io/composition: {{ .name }}
        {{- range .components }}
        {{ . }}: "1"
        {{- end }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          env:
            - name: TOA_ENV
              value: {{ $.Values.environment }}
              {{- if $.Values.variables }}
                {{- range $component := .components }}
                  {{- range $key, $vars := $.Values.variables }}
                    {{- if eq $component $key }}
                      {{- range $vars }}
            - name: {{ .name }}
                {{- if .value }}
              value: {{ .value | quote }}
                {{- end }}
                {{- if .secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secret.name }}
                  key: {{ .secret.key }}
                  optional: false
                {{- end }}
                      {{- end }}
                    {{- end }}
                  {{- end }}
                {{- end }}
                {{- range $.Values.variables.system }}
            - name: {{ .name }}
                {{- if .value }}
              value: {{ .value | quote }}
                {{- end }}
                {{- if .secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secret.name }}
                  key: {{ .secret.key }}
                  optional: false
                {{- end }}
                {{- end }}
              {{- end }}
---
{{- end }}
