$schema: https://json-schema.org/draft/2019-09/schema
$id: https://schemas.toa.io/0.0.0/context

type: object
properties:
  runtime:
    oneOf:
      - $ref: 'definitions#/definitions/version'
      - const: .
  version:
    $ref: 'definitions#/definitions/version'
  name:
    $ref: 'definitions#/definitions/token'
  description:
    type: string
  packages:
    type: string
  registry:
    type: string
  compositions:
    type: array
    minItems: 1
    items:
      type: array
      minItems: 1
      items:
        type: string
required: [runtime, name, packages, registry]
additionalProperties: false
