$schema: https://json-schema.org/draft/2019-09/schema
$id: https://schemas.toa.io/0.0.0/context

type: object
properties:
  runtime:
    properties:
      version:
        $ref: 'definitions#/definitions/version'
      registry:
        type: string
        format: uri
      proxy:
        type: string
        format: uri
    required: [version]
  version:
    $ref: 'definitions#/definitions/version'
  name:
    $ref: 'definitions#/definitions/token'
  description:
    type: string
  packages:
    type: string
  registry:
    type: string
  compositions:
    type: array
    minItems: 1
    items:
      type: object
      properties:
        name:
          $ref: 'definitions#/definitions/token'
        components:
          type: array
          minItems: 1
          items:
            $ref: 'definitions#/definitions/locator'
      required: [name, components]
required: [runtime, name, packages, registry]
additionalProperties: false
