version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.9.5-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      default:
        aliases:
          - system-rabbitmq
          - messages-rabbitmq
          - stats-rabbitmq
          - credits-rabbitmq
          - dummies-rabbitmq
  mongodb:
    image: mongo:5.0.2
    ports:
      - '27017:27017'
    networks:
      default:
        aliases:
          - messages-mongodb
          - stats-mongodb
          - credits-mongodb
          - dummies-mongodb
  toa:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:delegated
    command: /bin/sh -c "while sleep 1000; do :; done"
