$schema: https://json-schema.org/draft/2019-09/schema
$id: https://schemas.toa.io/0.0.0/rtd

definitions:
  resource:
    patternProperties:
      ^(\/([^\/#\?]+)?)+\/?$:
        $ref: '#/definitions/resource'
    properties:
      operations:
        type: array
        uniqueItems: true
        minItems: 1
        items:
          type: object
          properties:
            operation:
              $ref: definitions#/definitions/token
            type:
              enum: [transition, observation, assignment]
            query:
              type: boolean
          additionalProperties: false
    additionalProperties: false

$ref: '#/definitions/resource'
not:
  required: [operations]
