$schema: https://json-schema.org/draft/2019-09/schema
$id: https://schemas.toa.io/0.0.0/storages/mongodb

definitions:
  node:
    oneOf:
      - $ref: '#/definitions/locator'
      - type: object
        patternProperties:
          '.*':
            $ref: '#/definitions/node'
  locator:
    type: string
    pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$'

type: object
patternProperties:
  '.*':
    $ref: '#/definitions/node'
