$schema: https://json-schema.org/draft/2019-09/schema
$id: https://schemas.toa.io/0.0.0/context

type: object
properties:
  version:
    type: string
  name:
    type: string
    pattern: ^([a-zA-Z]+([_a-zA-Z0-9]*[a-zA-Z0-9]+)?)(-([a-zA-Z]+([_a-zA-Z0-9]*[a-zA-Z0-9]+)?))*$
  description:
    type: string
  packages:
    type: string
    default: components/*
  build:
    type: object
    properties:
      command:
        type: string
  runtime:
    type: object
    properties:
      version:
        type: string
      registry:
        type: string
        format: uri
      proxy:
        type: string
        format: uri
    required: [version]
  environment:
    type: string
  registry:
    type: object
    properties:
      base:
        type: string
      platforms:
        type: array
        nullable: true
        minItems: 1
        items:
          type: string
        default:
          - linux/amd64
          - linux/arm/v7
          - linux/arm64
    required: [base, platforms]
  compositions:
    type: array
    minItems: 1
    items:
      type: object
      properties:
        name:
          type: string
          pattern: ^[a-zA-Z]([a-zA-Z0-9]{1,31})?$
        image:
          type: string
        components:
          type: array
          minItems: 1
          items:
            type: string
            pattern: ^([a-zA-Z]+([_a-zA-Z0-9]*[a-zA-Z0-9]+)?)(\.([a-zA-Z]+([_a-zA-Z0-9]*[a-zA-Z0-9]+)?))$
      required: [name, components]
  annotations:
    type: object
required: [runtime, name, registry]
additionalProperties: false
