apiVersion: v1
kind: Service
metadata:
  name: messages-mongodb
spec:
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: credits-mongodb
spec:
  selector:
    app.kubernetes.io/name: rabbitmq
  ports:
    - port: 27017
      targetPort: 27017
