name: Publish

on:
#  pull_request:
#    types: [closed]
#    branches:
#      - main
#      - dev
  push:
    branches:
      - main
      - dev

jobs:
  publish:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16  # TODO: matrix

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install
        run: npm ci

      - name: Test
        run: npm test

      - name: Publish
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
  
          if [ ${{ github.base_ref }} = dev ]; then
            npx lerna publish --conventional-prerelease --preid dev --yes
          else
            npx lerna publish --conventional-graduate --yes
          fi
