name: Publish packages

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16  # TODO: matrix

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-          

      - name: Install
        run: npm ci

      - name: Test
        run: npm test

      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          
          if [ ${{ github.base_ref }} = main ]; then
            npm version minor --workspaces --include-workspace-root --no-commit-hooks --no-workspaces-update -m "chore: bump version" --no-git-tag-vesion
            npm publish --workspaces
            git commit -am "chore: bump version"
            git checkout dev
            git merge main
            git push
          else
            npm version prerelease --workspaces --include-workspace-root --no-commit-hooks --no-workspaces-update --preid dev --no-git-tag-version
            git commit -am "chore: bump version"
            git push
            npm publish --workspaces --tag dev
          fi
